export const SUBJECT_CATEGORY_LIST = [
  'JAVA',
  'JAVASCRIPT',
  'PYTHON',
  'SPRING',
  'REACT',
  'NODEJS',
  'DJANGO',
  'RDB',
  'NOSQL',
  'OS',
  'SECURITY',
  'NETWORK',
  'DATA_STRUCTURE',
  'ALGORITHM',
  'COMPILER',
  'TROUBLE',
  'DESIGN',
  'TEST',
  'INFRA',
  'CONTAINER',
  'DEVOPS',
  'COMMUNICATION',
  'WORK',
  'TECH',
  'CODING_TEST',
];
export const CAREER_TYPE_LIST = ['OVER_3', 'OVER_1', 'UNDER_1'];
export const SELET_TITLE_LIST = ['학습경력', '1순위', '2순위', '3순위'];
